#!/bin/sh

set -e
ARCH=$(uname -m)

case "$ARCH" in
    x86_64 | sparc64 | s390x | ppc64 | aarch64)
        LIB_DIR=/usr/lib64/interbase/bin
        SECONDARY_LIB_DIR=/usr/lib/interbase/bin
        ;;
    *)
        LIB_DIR=/usr/lib/interbase/bin
        SECONDARY_LIB_DIR=/usr/lib64/interbase/bin
        ;;
esac

if [ ! -x "$LIB_DIR"/fb_config ]; then
    LIB_DIR=$SECONDARY_LIB_DIR
fi

exec "$LIB_DIR"/fb_config "$@"
