Summary:	Firebird SQL Database Server and Client tools
Summary(pl):	Firebird - serwer baz danych SQL oraz narzêdzia klienckie
Name:		Firebird
# FirebirdCS/FirebirdSS (Classic Server/Super Server)?
Version:	1.0.0.796
Release:	1
License:	Interbase Public License 1.0
Group:		Applications/Databases
Source0:	ftp://ftp.sourceforge.net/pub/sourceforge/firebird/%{name}-%{version}.src.tar.gz
Source1:	ftp://ftp.sourceforge.net/pub/sourceforge/firebird/bootkit-%{version}.tar.gz
# missing isc4.gbak generated by: make isql || : ; make gdef gsec secutity_db
Source2:	%{name}-isc4.gbak
# missing save.c generated by gpre after building pixar w/o save.o and then other stuff
Patch0:		%{name}-bootkit-missing.patch
# dirty "fixes" for missing error contants and conflict with isql from unixODBC
Patch1:		%{name}-fix.patch
# ksh supports only [! ] globs, not [^ ]
Patch2:		%{name}-ksh.patch
URL:		http://firebird.sourceforge.net/
Requires:	%{name}-lib = %{version}
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%define		ibdir	%{_libdir}/interbase

%description
Firebird is a powerful, high-performance relational database designed
to be embedded into applications on multiple platforms.

%description -l pl
Firebird jest potê¿nym, wysoko wydajnym systemem relacyjnych baz
danych zaprojektowanym do osadzania w aplikacjach na wielu
platformach.

%package lib
Summary:	Firebird shared library
Summary(pl):	Biblioteka wspó³dzielona Firebird
Group:		Libraries

%description lib
Firebird shared library (libgds).

%description lib -l pl
Biblioteka wspó³dzielona Firebird (libgds).

%package devel
Summary:	Header files for Firebird library
Summary(pl):	Pliki nag³ówkowe biblioteki Firebird
Group:		Development/Libraries
Requires:	%{name}-lib = %{version}

%description devel
Header files for Firebird library.

%description devel -l pl
Pliki nag³ówkowe biblioteki Firebird.

%package static
Summary:	Static Firebird library
Summary(pl):	Statyczna biblioteka Firebird
Group:		Development/Libraries
Requires:	%{name}-devel = %{version}

%description static
Static Firebird library (libgds).

%description static -l pl
Statyczna biblioteka Firebird (libgds).

%prep
%setup -q -n firebird-%{version} -a1
%patch0 -p1
%patch1 -p1
%patch2 -p1

chmod u+w -R .
cp -f %{SOURCE2} misc/isc4.gbak

%build
INTERBASE=/usr/lib/interbase; export INTERBASE
echo 'y' | ./Configure.sh PROD
. ./Configure_SetupEnv.sh

%{__make} firebird \
	CC="%{__cc}" \
	PROD_CFLAGS="%{rpmcflags} -fpic -DFLINTSTONE"

# classic/super - what's the difference?
#%{__make} super_firebird

#-Isource/interbase/include"

%install
rm -rf $RPM_BUILD_ROOT
INTERBASE=/usr/lib/interbase; export INTERBASE
. ./Configure_SetupEnv.sh

%{__make} buildclassicimage -f firebird/install/linux/Makefile

install -d $RPM_BUILD_ROOT{%{ibdir},%{_libdir},%{_includedir}} \
	$RPM_BUILD_ROOT%{_examplesdir}/%{name}-%{version}
cd buildroot/opt/interbase
rm -f bin/isc4.gbak
cp -af UDF bin help intl interbase.msg isc4.gdb isc_config \
	$RPM_BUILD_ROOT%{ibdir}
install include/* $RPM_BUILD_ROOT%{_includedir}
install lib/* $RPM_BUILD_ROOT%{_libdir}
install examples/* $RPM_BUILD_ROOT%{_examplesdir}/%{name}-%{version}

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc builds_win32/install/{*License,Readme}.txt
%attr(755,root,root) %{_libdir}/libib_util.so
%dir %{ibdir}
%attr(755,root,root) %{ibdir}/UDF
%attr(755,root,root) %{ibdir}/bin
%{ibdir}/help
%{ibdir}/intl
%{ibdir}/interbase.msg
# following two files should be in /var and /etc resp.?
%{ibdir}/isc4.gdb
%{ibdir}/isc_config

%files lib
%defattr(644,root,root,755)
# .so link needed here - library doesn't have SONAME
%attr(755,root,root) %{_libdir}/libgds.so*

%files devel
%defattr(644,root,root,755)
%{_includedir}/*
%{_examplesdir}/%{name}-%{version}

%files static
%defattr(644,root,root,755)
%{_libdir}/libgds.a
